services:
  dnd-db:
    container_name: dnd-db
    platform: linux/x86_64
    image: mysql:latest
    expose:
      - "3306"
    volumes:
      - ./dnd-db:/docker-entrypoint-initdb.d
    ports:
      - "3406:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: characters
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
  dnd-python:
    container_name: dnd-python
    platform: linux/x86_64
    build:
      context: ./
      dockerfile: Dockerfile
    image: dnd_app:latest
    ports:
      - "8080:5000"
    depends_on:
      - dnd-db
    restart: always
