services:
  db:
    container_name: dnd-db
    platform: linux/x86_64
    image: mysql:9.1.0
    expose:
      - "3306"
    volumes:
      - ./dnd-db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    ports:
      - "3406:3306"
    env_file: .env
    restart: always
  python:
    container_name: dnd-python
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/dnd
    env_file: .env
    ports:
      - "8080:5000"
    depends_on:
      - db
    restart: always
    command: ["gunicorn", "main:app", "-b", "0.0.0.0:5000", "-w", "4", "--reload"]

volumes:
  db_data: