apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: dnd-db
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: MYSQL_DATABASE
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: MYSQL_USER
          image: mysql:9.1.0
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: db-configmap
              mountPath: /docker-entrypoint-initdb.d
            - name: db-data
              mountPath: /var/lib/mysql
          resources:
            requests:
              memory: "768Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      restartPolicy: Always
      volumes:
        - name: db-configmap
          configMap:
            name: db-configmap
        - name: db-data
          persistentVolumeClaim:
            claimName: db-pv-claim
