apiVersion: v1
kind: Service
metadata:
  name: dnd-db
spec:
  ports:
    - name: "3406"
      port: 3406
      targetPort: 3306
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    app: db
